version: '3'
services:
  theos:
    hostname: 'theos'
    restart: always
    build: .
    container_name: 'theos'
    working_dir: '/tweaks'
    tty: true
    volumes:
      - ./tweaks:/tweaks
      - ./tmp/toolchain:/theos/toolchain
      - ./tmp/sdks:/theos/sdks
